disabled terraform workflow
NASA-PDS/nucleus pull request #57
Opened 2023-07-13 23:24 UTC by sjoshi-jpl

## 🗒️ Summary
Since all nucleus resources are already deployed to NGAP, terraform workflow has been disabled to avoid merging errors.

## ⚙️ Test Data and/or Report
One of the following should be included here:
* Reference to regression test included in code (preferred wherever reasonable)
* Attach test data here + outputs of tests

## ♻️ Related Issues

Ref - https://github.com/NASA-PDS/operations/issues/367

2023-07-13 23:42 UTC, ramesh-maddegoda approved these changes

2023-07-14 00:02 UTC, sjoshi-jpl commented
@tloubrieu-jpl can I merge this?

2023-07-14 00:08 UTC, nutjob4life requested changes
Minor change

2023-07-14 00:08 UTC, nutjob4life commented on terraform/main.tf
> +# module "ecs" {
Whenever something is commented-out, I like to see a one-line explanation as to why. It causes less worry in the future!

2023-07-14 15:10 UTC, nutjob4life approved these changes

2023-07-14 15:11 UTC, merged